<?php

/**
 *@file
 * This module has a custom functionality for Invati Phase 2 project.
 * Provides API integration with the FeedMagnet service.
 */

/**
 * Implements hook_menu().
 */
function invati_fm_menu() {
  $items['admin/config/invati'] = array(
    'title' => 'Invati',
    'description' => 'Invati settings.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );  

  $items['admin/config/invati/feedmagnet'] = array(
    'title' => 'FeedMagneet',
    'description' => 'Configure integration with FeedMagnet API services.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('invati_fm_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'invati_fm.admin.inc',
  );
  
  return $items;
}

/**
*Implements hook_block_info().
*/
function invati_fm_block_info() {
  $blocks = array();
  
  $blocks['community_newsfeed_pc'] = array(
    'info' => t('Invati: Community Newsfeed PC'), 
  );
  
  $blocks['community_newsfeed_mobile'] = array(
    'info' => t('Invati: Community Newsfeed Mobile'), 
  );
  
  $blocks['community_newsfeed_teaser_mobile'] = array(
    'info' => t('Invati: Community Newsfeed Teaser Mobile'), 
  );
  
  return $blocks;
}

/**
 * Iplements hook_block_view().
 */ 
function invati_fm_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'community_newsfeed_pc':
      $block['subject'] = t('Community Posts');
      $block['content'] = theme('invati_fm_community_newsfeed_pc');
      break;
    case 'community_newsfeed_mobile':
      $block['subject'] = t('Community Posts');
      $block['content'] = theme('invati_fm_community_newsfeed_mobile');
      break;
    case 'community_newsfeed_teaser_mobile':
      $block['subject'] = t('Community Posts');
      $block['content'] = theme('invati_fm_community_newsfeed_teaser_mobile');
      break;
  } 
  return $block;
}

/**
 * Implements hook_theme().
 */ 
function invati_fm_theme() {
  return array(
    'invati_fm_community_newsfeed_pc' => array(
      'file' => 'invati_fm.theme.inc',
      'template' => 'invati-fm-community-newsfeed-pc',
    ),
    'invati_fm_community_newsfeed_mobile' => array(
      'file' => 'invati_fm.theme.inc',
      'template' => 'invati-fm-community-newsfeed-mobile',
    ),
    'invati_fm_community_newsfeed_teaser_mobile' => array(
      'file' => 'invati_fm.theme.inc',
      'template' => 'invati-fm-community-newsfeed-teaser-mobile',
    ),
  );
}